//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.HealthVault.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.HealthVault.Web.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action links can only be used on pages with view state enabled..
        /// </summary>
        internal static string ActionLinksRequireViewState {
            get {
                return ResourceManager.GetString("ActionLinksRequireViewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActionLabels and ActionCommands properties must contain the same number of elements..
        /// </summary>
        internal static string ActionParamLengthsNotEqual {
            get {
                return ResourceManager.GetString("ActionParamLengthsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument value cannot be null..
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the config key &apos;{0}&apos; is either absent in the config settings or is malformed..
        /// </summary>
        internal static string ConfigValueAbsentOrMalformed {
            get {
                return ResourceManager.GetString("ConfigValueAbsentOrMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie is too large..
        /// </summary>
        internal static string CookieTooBig {
            get {
                return ResourceManager.GetString("CookieTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method name must be provided..
        /// </summary>
        internal static string CtorMethodNameNullOrEmpty {
            get {
                return ResourceManager.GetString("CtorMethodNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HealthServiceDataGrid control can only be used in pages derived from HealthServicePage..
        /// </summary>
        internal static string DataGridInHealthServicePageOnly {
            get {
                return ResourceManager.GetString("DataGridInHealthServicePageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Decompress() method can only decompress a maximum of 64KB of data..
        /// </summary>
        internal static string DecompressionSizeExceeded {
            get {
                return ResourceManager.GetString("DecompressionSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: You do not have access to all items returned for this record..
        /// </summary>
        internal static string FilteredResults {
            get {
                return ResourceManager.GetString("FilteredResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string HistoryAuditActionChanged {
            get {
                return ResourceManager.GetString("HistoryAuditActionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created new entry.
        /// </summary>
        internal static string HistoryAuditActionCreated {
            get {
                return ResourceManager.GetString("HistoryAuditActionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string HistoryAuditActionDeleted {
            get {
                return ResourceManager.GetString("HistoryAuditActionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string HistoryAuditActionUnknown {
            get {
                return ResourceManager.GetString("HistoryAuditActionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known HealthVault web-service instance with the given ID was found..
        /// </summary>
        internal static string InstanceIdNotFound {
            get {
                return ResourceManager.GetString("InstanceIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An authenticated connection cannot be created without an authentication token being present..
        /// </summary>
        internal static string NeedAuthToken {
            get {
                return ResourceManager.GetString("NeedAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items were found..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user must be logged in to perform this operation..
        /// </summary>
        internal static string PersonNotLoggedIn {
            get {
                return ResourceManager.GetString("PersonNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Cookie version: {0}..
        /// </summary>
        internal static string UnknownCookieVersion {
            get {
                return ResourceManager.GetString("UnknownCookieVersion", resourceCulture);
            }
        }
    }
}
