// This file lists existing suppressions
// Feel free to delete lines when you fix the underlying issue.
// You should never add to this file; if you must suppress an FxCop warning, put the suppression inline.
// If you absolutely MUST add to this file, you can run 'oacr fxcop <project> /target <assembly>'
// where <project> is HealthVault or HealthVault_SDK and assembly is the dll you're building, including extension. 
// This will launch the fxcop gui. Click Analyze, then rightclick the error and select Copy As -> Module level suppression. Paste here.

using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Health.ItemTypes.Message.#Headers")]
[module: SuppressMessage("Microsoft.Design", "CA1013:OverloadOperatorEqualsOnOverloadingAddAndSubtract", Scope = "member", Target = "Microsoft.Health.ItemTypes.WeightValue.#op_Subtraction(Microsoft.Health.ItemTypes.WeightValue,Microsoft.Health.ItemTypes.WeightValue)")]
[module: SuppressMessage("Microsoft.Design", "CA1012:AbstractTypesShouldNotHaveConstructors", Scope = "type", Target = "Microsoft.Health.ItemTypes.Measurement`1")]
[module: SuppressMessage("Microsoft.Design", "CA1012:AbstractTypesShouldNotHaveConstructors", Scope = "type", Target = "Microsoft.Health.ItemTypes.Range`1")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Annotation.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSampleTwoValue.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSampleTwoValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamplesData.#StoreTwo()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamplesData.#StoreSingle()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamplesData.#CreateSingleValuedSamples()", MessageId = "System.Double.Parse(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamplesData.#CreateTwoValuedSamples()", MessageId = "System.Double.Parse(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryRelative.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicationFill.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.WeightGoal.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.WeightGoal.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.WeightGoal.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DurationValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.LifeGoal.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.StructuredMeasurement.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.StructuredMeasurement.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryPerson.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Name.#ToString()", MessageId = "System.String.Format(System.String,System.Object[])")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.TestResultRangeValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ContactInfo.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjection.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Alert.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Procedure.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Procedure.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfile.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfile.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfileV2.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfileV2.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateDate.#ToString(System.IFormatProvider)", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodOxygenSaturation.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults.#WriteXml(System.Xml.XmlWriter)", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyDimension.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Person.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicData.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicData.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicData.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSampleOneValue.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSampleOneValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DoseValue.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DoseValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DoseValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object[])")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DoseValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.HeartRate.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DoubleRange.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistory.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.HbA1C.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DiabeticProfile.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.TestResultRange.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhalerUse.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhalerUse.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Exercise.#ToString()", MessageId = "System.Double.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjectionUse.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryV3.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSegment.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.GroupMembershipType.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Basic.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Basic.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.DisplayValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Length.#GetValueString(System.Double)", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Immunization.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#StoreSnpItems()", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#CreateSnpItems()", MessageId = "System.Int32.Parse(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Payer.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.SleepJournalAM.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1307:SpecifyStringComparison", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateDateTime.#CompareTo(Microsoft.Health.ItemTypes.ApproximateDateTime)", MessageId = "System.String.CompareTo(System.String)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.Assessment.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyCompositionValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyCompositionValue.#ToString()", MessageId = "System.String.Format(System.String,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.CalorieGuideline.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodPressure.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.RespiratoryProfile.#ToString()", MessageId = "System.Text.StringBuilder.AppendFormat(System.String,System.Object[])")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicWeeklyGoal.#ToString()", MessageId = "System.String.Format(System.String,System.Object,System.Object)")]
[module: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicData.#WriteXml(System.String,System.Xml.XmlWriter)")]
[module: SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Microsoft.Health.ItemTypes.ItemTypeRegistrar")]
[module: SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.Health.ItemTypes.ItemTypeRegistrar.#.cctor()")]
[module: SuppressMessage("Microsoft.MSInternal", "CA900:AptcaAssembliesShouldBeReviewed")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.VitalSignsResultType.#Flag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabResultType.#Flags", MessageId = "Flags")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeries.#SeriesInstanceUID", MessageId = "UID")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Heartrate_BPM", MessageId = "Heartrate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Heartrate_BPM", MessageId = "BPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#AerobicSteps_count", MessageId = "count")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Pace_s_per_100m", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Pace_s_per_100m", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Pace_s_per_100m", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Steps_count", MessageId = "count")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Altitude_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Temperature_celsius", MessageId = "celsius")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Torque_Nm", MessageId = "Nm")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Speed_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Speed_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Speed_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#AirPressure_kPa", MessageId = "Pa")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#AirPressure_kPa", MessageId = "k")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Power_watts", MessageId = "watts")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Cadence_RPM", MessageId = "RPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Distance_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudy.#StudyInstanceUID", MessageId = "UID")]
[module: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Microsoft.Health.ItemTypes.Encounter.#Type")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.CCD", MessageId = "CCD")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#Fev6", MessageId = "Fev")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#Fev1", MessageId = "Fev")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#MeasurementFlags", MessageId = "Flags")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.PeakFlow.#Pef", MessageId = "Pef")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodGlucoseMeasurement.#.ctor(System.Double)", MessageId = "millimoles")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodGlucoseMeasurement.#.ctor(System.Double,Microsoft.Health.ItemTypes.DisplayValue)", MessageId = "millimoles")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfile.#LDL", MessageId = "LDL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfile.#HDL", MessageId = "HDL")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodOxygenSaturation.#MeasurementFlags", MessageId = "Flags")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults.#dbSnpBuild", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults.#dbSnpBuild", MessageId = "db")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GeneticSnpResults.#SnpData", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateTime.#op_Equality(Microsoft.Health.ItemTypes.ApproximateTime,System.Object)", MessageId = "obj")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateTime.#op_Inequality(Microsoft.Health.ItemTypes.ApproximateTime,System.Object)", MessageId = "obj")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateTime.#op_GreaterThan(Microsoft.Health.ItemTypes.ApproximateTime,System.Object)", MessageId = "obj")]
[module: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateTime.#op_LessThan(Microsoft.Health.ItemTypes.ApproximateTime,System.Object)", MessageId = "obj")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.HeartRate.#MeasurementFlags", MessageId = "Flags")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.HbA1C", MessageId = "Hb")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.HbA1C", MessageId = "Hb")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DiabeticProfile.#MaximumHbA1C", MessageId = "Hb")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DiabeticProfile.#MaximumHbA1C", MessageId = "Hb")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.CCR", MessageId = "CCR")]
[module: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Microsoft.Health.ItemTypes.Organization.#Type")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjectionMeasurement.#.ctor(System.Double)", MessageId = "i")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjectionMeasurement.#.ctor(System.Double,Microsoft.Health.ItemTypes.DisplayValue)", MessageId = "i")]
[module: SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix", Scope = "type", Target = "Microsoft.Health.ItemTypes.Measurement`1", MessageId = "T")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumTorque_Nm", MessageId = "Nm")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#CaloriesBurned_calories", MessageId = "calories")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#Steps_count", MessageId = "count")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageCadence_RPM", MessageId = "RPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumSpeed_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumSpeed_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumSpeed_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageTemp_celsius", MessageId = "celsius")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AveragePace_s_per_100m", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AveragePace_s_per_100m", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AveragePace_s_per_100m", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#FatCaloriesBurned_calories", MessageId = "calories")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumCadence_RPM", MessageId = "RPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumTorque_Nm", MessageId = "Nm")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AerobicSteps_count", MessageId = "count")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumHeartrate_BPM", MessageId = "Heartrate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumHeartrate_BPM", MessageId = "BPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumCadence_RPM", MessageId = "RPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedDescending_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedDescending_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedDescending_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#EnergyFromFatOld_kJ", MessageId = "k")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageTorque_Nm", MessageId = "Nm")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageAltitude_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#Odometer_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumPower_watts", MessageId = "watts")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumSpeed_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumSpeed_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumSpeed_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumTemp_celsius", MessageId = "celsius")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumPace_s_per_100m", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumPace_s_per_100m", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumPace_s_per_100m", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#ElevationGain_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumTemp_celsius", MessageId = "celsius")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumPace_s_per_100m", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumPace_s_per_100m", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumPace_s_per_100m", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MinimumAltitude_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumAltitude_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#PeakHeartrate_BPM", MessageId = "Heartrate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#PeakHeartrate_BPM", MessageId = "BPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumHeartrate_BPM", MessageId = "Heartrate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumHeartrate_BPM", MessageId = "BPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AerobicStepDuration_minutes", MessageId = "minutes")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#Work_kJ", MessageId = "k")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedAscending_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedAscending_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedAscending_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AveragePower_watts", MessageId = "watts")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#EnergyOld_kJ", MessageId = "k")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedAscending_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedAscending_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumVerticalSpeedAscending_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageHeartrate_BPM", MessageId = "Heartrate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageHeartrate_BPM", MessageId = "BPM")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#LeftRightBalance_percent", MessageId = "percent")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#ElevationLoss_meters", MessageId = "meters")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageSpeed_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageSpeed_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageSpeed_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedDescending_m_per_s", MessageId = "m")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedDescending_m_per_s", MessageId = "s")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#AverageVerticalSpeedDescending_m_per_s", MessageId = "per")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseDetail.#MaximumPower_watts", MessageId = "watts")]
[module: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultValue.#Flag", MessageId = "Flag")]
[module: SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix", Scope = "type", Target = "Microsoft.Health.ItemTypes.Range`1", MessageId = "T")]
[module: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Health.ItemTypes.CodableValue")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.SnpItem", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpItem.#.ctor(System.String,System.String,System.String,System.String,System.Int32,System.Int32)", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpItem.#ReferenceSnpId", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.CDA", MessageId = "CDA")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.Health.ItemTypes.SnpData", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#SnpItems", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#RefreshSnpItems()", MessageId = "Snp")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ClaimAmounts.#CoPayment", MessageId = "CoPayment")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ClaimAmounts.#.ctor(System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal,System.Decimal)", MessageId = "coPayment")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultGroup.#SubGroups", MessageId = "SubGroups")]
[module: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#Type")]
[module: SuppressMessage("Microsoft.Performance", "CA1824:MarkAssembliesWithNeutralResourcesLanguage")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamplesData.#.ctor(Microsoft.Health.OtherItemData)")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#.ctor(Microsoft.Health.OtherItemData)")]
[module: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Scope = "member", Target = "Microsoft.Health.ItemTypes.SnpData.#CreateSnpItems()", MessageId = "csvStringValueBuffer")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryRelativeV3.#Relationship")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryRelativeV3.#RegionOfOrigin")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CarePlanTaskRecurrence.#Interval")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CarePlanGoalGroup.#Goals")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CarePlanGoal.#GoalRanges")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ConditionEntry.#Severity")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ConditionEntry.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ConditionEntry.#Occurrence")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.File.#ContentType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Baby.#Gender")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryRelative.#Relationship")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.VitalSignsResultType.#Flag")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.VitalSignsResultType.#Title")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.VitalSignsResultType.#Unit")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicationFill.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabResultType.#Unit")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeries.#BodyPart")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeries.#Modality")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.StructuredMeasurement.#Units")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.FamilyHistoryPerson.#Relationship")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSamples.#Unit")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Name.#Suffix")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Name.#Title")]
[module: SuppressMessage("Microsoft.Usage", "CA2225:OperatorOverloadsHaveNamedAlternates", Scope = "member", Target = "Microsoft.Health.ItemTypes.WeightValue.#op_Subtraction(Microsoft.Health.ItemTypes.WeightValue,Microsoft.Health.ItemTypes.WeightValue)")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#BloodType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#Ethnicity")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#HighestEducationLevel")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#Religion")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Personal.#MaritalStatus")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudy.#Reason")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MicrobiologyLabResults.#SpecimenType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MicrobiologyLabResults.#OrganismName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MicrobiologyLabResults.#SensitivityValue")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MicrobiologyLabResults.#SensitivityAgent")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Encounter.#Type")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Pregnancy.#ConceptionMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultDetails.#Substance")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultDetails.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultDetails.#ClinicalCode")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultDetails.#CollectionMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjection.#InsulinType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Procedure.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Procedure.#AnatomicLocation")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodGlucose.#GlucoseMeasurementType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodGlucose.#MeasurementContext")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HealthAssessment.#Category")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Concern.#Description")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Concern.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodOxygenSaturation.#MeasurementFlags")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BloodOxygenSaturation.#MeasurementMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyDimension.#MeasurementName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HealthServiceDateTime.#TimeZone")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Person.#PersonType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AerobicData.#Mode")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HeartRate.#MeasurementMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HeartRate.#MeasurementFlags")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HeartRate.#MeasurementConditions")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HbA1C.#AssayMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.TestResultRange.#RangeType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.TestResultRange.#Text")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Delivery.#Outcome")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Delivery.#DeliveryMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Organization.#Type")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Health.ItemTypes.Measurement`1.#.ctor(!0)")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Health.ItemTypes.Measurement`1.#.ctor(!0,Microsoft.Health.ItemTypes.DisplayValue)")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.QuestionAnswer.#Question")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Contraindication.#Substance")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Contraindication.#Source")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Contraindication.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhalerUse.#DosePurpose")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhalerUse.#Drug")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhalerUse.#Strength")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#DrugName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#UsageSchedule")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#PrescriptionType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#DrugForm")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#PurposeOfUse")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DailyMedicationUsage.#SingleDoseDescription")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhaler.#Drug")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AsthmaInhaler.#Strength")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestType.#Substance")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestType.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestType.#CollectionMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Exercise.#Activity")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Language.#SpokenLanguage")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Health.ItemTypes.Range`1.#.ctor()")]
[module: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Microsoft.Health.ItemTypes.Range`1.#.ctor(!0,!0)")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.InsulinInjectionUse.#InsulinType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ExerciseSegment.#Activity")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AllergicEpisode.#Treatment")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AllergicEpisode.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.AllergicEpisode.#Reaction")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GroupMembershipType.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyComposition.#MeasurementMethod")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyComposition.#Site")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BodyComposition.#MeasurementName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.PersonItem.#PersonType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Immunization.#Manufacturer")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Immunization.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Immunization.#AnatomicSurface")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Immunization.#Route")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Medication.#Indication")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Medication.#Prescribed")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Medication.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Medication.#GenericName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Medication.#Route")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Payer.#CoverageType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.SleepJournalAM.#Medications")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ApproximateDateTime.#TimeZone")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Directive.#ProhibitedInterventions")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Allergy.#Reaction")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Allergy.#AllergenType")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Allergy.#Treatment")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Allergy.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Allergy.#AllergenCode")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Assessment.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Assessment.#Value")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Assessment.#Group")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultGroup.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.LabTestResultGroup.#GroupName")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Appointment.#Service")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Appointment.#CareClass")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Appointment.#Specialty")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Appointment.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CalorieGuideline.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Prescription.#Substitution")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Prescription.#Instructions")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Condition.#Name")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Condition.#Status")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#AdmittingDiagnosis")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#PrincipalDiagnosis")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#Setting")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#AdditionalDiagnosis")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#Type")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#Category")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#AdditionalProcedure")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DischargeSummary.#PrincipalProcedure")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudyV2.#Reason")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeriesV2.#Modality")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeriesV2.#BodyPart")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.HealthJournalEntry.#Category")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.Comment.#Category")]
[module: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Microsoft.Health.ItemTypes.BlueButtonTextFile.#SourceFormat")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudyV2.#StudyInstanceUID", MessageId = "UID")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.MedicalImageStudySeriesV2.#SeriesInstanceUID", MessageId = "UID")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DietaryIntake.#FolateDFE", MessageId = "Folate")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DietaryIntake.#FolateDFE", MessageId = "DFE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.DietaryIntake.#VitaminARAE", MessageId = "ARAE")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GoalAssociatedTypeInfo.#ThingTypeDisplayXpath", MessageId = "Xpath")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.GoalAssociatedTypeInfo.#ThingTypeValueXpath", MessageId = "Xpath")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ConcentrationMeasurement.#.ctor(System.Double)", MessageId = "millimoles")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.ConcentrationMeasurement.#.ctor(System.Double,Microsoft.Health.ItemTypes.DisplayValue)", MessageId = "millimoles")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfileV2.#LDL", MessageId = "LDL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.Health.ItemTypes.CholesterolProfileV2.#HDL", MessageId = "HDL")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="Microsoft.Health.ItemTypes.DietaryIntakeItem.#VitaminARAE", MessageId="ARAE")]
[module: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope="member", Target="Microsoft.Health.ItemTypes.DietaryIntakeItem.#FolateDFE", MessageId="DFE")]