// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HealthVault.Client.Models
{
    using HealthVault.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The goal response.
    /// </summary>
    public partial class GoalsResponse
    {
        /// <summary>
        /// Initializes a new instance of the GoalsResponse class.
        /// </summary>
        public GoalsResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GoalsResponse class.
        /// </summary>
        /// <param name="goals">The collection of goals</param>
        /// <param name="nextLink">The URI for the next page of data</param>
        public GoalsResponse(IList<Goal> goals = default(IList<Goal>), string nextLink = default(string))
        {
            Goals = goals;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the collection of goals
        /// </summary>
        [JsonProperty(PropertyName = "goals")]
        public IList<Goal> Goals { get; set; }

        /// <summary>
        /// Gets or sets the URI for the next page of data
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
