// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HealthVault.Client.Models
{
    using HealthVault.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftKhronosCloudCommonErrorsErrorInformation
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftKhronosCloudCommonErrorsErrorInformation class.
        /// </summary>
        public MicrosoftKhronosCloudCommonErrorsErrorInformation()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftKhronosCloudCommonErrorsErrorInformation class.
        /// </summary>
        public MicrosoftKhronosCloudCommonErrorsErrorInformation(string code = default(string), string message = default(string), string target = default(string), IList<MicrosoftKhronosCloudCommonErrorsErrorInformation> details = default(IList<MicrosoftKhronosCloudCommonErrorsErrorInformation>), MicrosoftKhronosCloudCommonErrorsErrorInformation innererror = default(MicrosoftKhronosCloudCommonErrorsErrorInformation), object exception = default(object))
        {
            Code = code;
            Message = message;
            Target = target;
            Details = details;
            Innererror = innererror;
            Exception = exception;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<MicrosoftKhronosCloudCommonErrorsErrorInformation> Details { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innererror")]
        public MicrosoftKhronosCloudCommonErrorsErrorInformation Innererror { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exception")]
        public object Exception { get; set; }

    }
}
