// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HealthVault.Client.Models
{
    using HealthVault.Client;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Onboarding response
    /// </summary>
    public partial class OnboardingResponse
    {
        /// <summary>
        /// Initializes a new instance of the OnboardingResponse class.
        /// </summary>
        public OnboardingResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OnboardingResponse class.
        /// </summary>
        /// <param name="invitationCode">Gets or sets the invitation
        /// code.</param>
        /// <param name="inviteUrl">Get Or Set the invite url</param>
        /// <param name="nextLink">The URI for the next page of data</param>
        public OnboardingResponse(string invitationCode = default(string), string inviteUrl = default(string), string nextLink = default(string))
        {
            InvitationCode = invitationCode;
            InviteUrl = inviteUrl;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the invitation code.
        /// </summary>
        [JsonProperty(PropertyName = "invitationCode")]
        public string InvitationCode { get; set; }

        /// <summary>
        /// Gets or sets get Or Set the invite url
        /// </summary>
        [JsonProperty(PropertyName = "inviteUrl")]
        public string InviteUrl { get; set; }

        /// <summary>
        /// Gets or sets the URI for the next page of data
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
